# Generated by Django 5.2.14 on 2026-05-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0005_add_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Venda'), ('trade', 'Troca'), ('both', 'Venda e Troca')], max_length=10),
        ),
    ]
