# Generated by Django 5.2.14 on 2026-05-28 00:51

import django.db.models.deletion
import marketplace_app.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0010_payment_delivery_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='trade_suggestions',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='TradeProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.TextField(blank=True)),
                ('cash_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('proposer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_proposals_made', to=settings.AUTH_USER_MODEL)),
                ('trade_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='marketplace_app.traderequest')),
            ],
        ),
        migrations.CreateModel(
            name='TradeFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_method', models.CharField(blank=True, choices=[('pix', 'PIX'), ('credit_card', 'Cartão de crédito'), ('debit_card', 'Cartão de débito'), ('bank_transfer', 'Transferência bancária')], max_length=20)),
                ('payment_status', models.CharField(choices=[('draft', 'Rascunho'), ('payment_pending', 'Aguardando confirmação do pagamento'), ('payment_confirmed', 'Pagamento confirmado'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='draft', max_length=20)),
                ('payment_checkout_token', models.CharField(blank=True, max_length=255)),
                ('payment_payload', models.JSONField(blank=True, default=dict)),
                ('payment_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_method', models.CharField(choices=[('pickup', 'Retirada presencial'), ('seller_shipping', 'Frete do vendedor'), ('platform_shipping', 'Frete da plataforma'), ('to_agree', 'A combinar')], default='to_agree', max_length=20)),
                ('recipient_name', models.CharField(blank=True, max_length=255)),
                ('recipient_phone', models.CharField(blank=True, max_length=20)),
                ('postal_code', models.CharField(blank=True, max_length=9)),
                ('street', models.CharField(blank=True, max_length=255)),
                ('number', models.CharField(blank=True, max_length=20)),
                ('complement', models.CharField(blank=True, max_length=100)),
                ('neighborhood', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('notes', models.TextField(blank=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trade_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fulfillment', to='marketplace_app.traderequest')),
                ('agreed_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fulfillments', to='marketplace_app.tradeproposal')),
            ],
        ),
    ]
