# Generated by Django 6.0.5 on 2026-06-05 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0016_add_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='shipped_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending_shipment', 'Aguardando envio'), ('shipped', 'Enviado'), ('received', 'Recebido')], default='pending_shipment', max_length=20),
        ),
    ]
