# Generated by Django 6.0.5 on 2026-06-06 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0017_order_item_fulfillment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradeproposal',
            name='cash_payer',
            field=models.CharField(blank=True, choices=[('requester', 'Quem solicitou a troca'), ('owner', 'Dono do anúncio')], max_length=12),
        ),
    ]
