# Generated by Django 6.0.5 on 2026-06-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0020_address_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='stock',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade disponível em estoque'),
        ),
    ]
