# Generated by Django 6.0.5 on 2026-06-06 16:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0021_listing_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreVerificationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='verification_docs/')),
                ('message', models.TextField(blank=True, help_text='Mensagem da loja ao administrador')),
                ('status', models.CharField(choices=[('pending', 'Em análise'), ('approved', 'Aprovada'), ('rejected', 'Recusada')], default='pending', max_length=20)),
                ('review_note', models.TextField(blank=True, help_text='Resposta do administrador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
