# Generated by Django 6.0.5 on 2026-06-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0022_store_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeprofile',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='store_banners/'),
        ),
        migrations.AddField(
            model_name='storeprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Descrição pública da loja'),
        ),
    ]
