# Generated by Django 6.0.5 on 2026-06-06 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0023_store_branding'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('prohibited', 'Conteúdo ofensivo ou ilegal'), ('off_topic', 'Fora do escopo (não é eletrônico/TI)'), ('scam', 'Golpe ou anúncio falso'), ('other', 'Outro')], default='other', max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('reviewed', 'Resolvida'), ('dismissed', 'Descartada')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='marketplace_app.listing')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
