# Generated by Django 6.0.5 on 2026-06-06 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0024_listing_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='strikes',
            field=models.PositiveIntegerField(default=0, help_text='Advertências por violação de conteúdo'),
        ),
    ]
