from django.urls import path
from . import views
from .views import ListingListAPIView

urlpatterns = [
    path('', views.home, name='home'),
    path('criar-anuncio/', views.criar_anuncio, name='criar_anuncio'),
    path('meus-anuncios/', views.my_listings, name='my_listings'),
    path('editar-perfil/', views.edit_profile, name='edit_profile'),
    path('alterar-senha/', views.change_password, name='change_password'),
    path('perfil/<str:username>/', views.user_profile, name='user_profile'),
    path('editar-anuncio/<int:pk>/', views.edit_listing, name='edit_listing'),
    path('excluir-anuncio/<int:pk>/', views.delete_listing, name='delete_listing'),
    path('anuncio/<int:pk>/', views.listing_detail, name='listing_detail'),
    path('carrinho/', views.cart_view, name='cart'),
    path('adicionar-carrinho/<int:pk>/', views.add_to_cart, name='add_to_cart'),
    path('remover-carrinho/<int:pk>/', views.remove_from_cart, name='remove_from_cart'),
    path('carrinho/item/<int:pk>/acao/', views.update_cart_item_action, name='update_cart_item_action'),
    path('checkout/', views.checkout_view, name='checkout'),
    path('historico/', views.history_view, name='history'),
    path('pedidos/', views.orders_view, name='orders'),
    path('pedidos/<int:pk>/', views.order_detail, name='order_detail'),
    path('pedidos/<int:pk>/entrega/', views.delivery_update, name='delivery_update'),
    path('trocas/', views.trade_requests_view, name='trade_requests'),
    path('trocas/<int:pk>/', views.trade_request_detail, name='trade_request_detail'),
    path('trocas/<int:pk>/checkout/', views.trade_checkout, name='trade_checkout'),
    path('trocas/<int:pk>/propostas/', views.trade_proposal_create, name='trade_proposal_create'),
    path('trocas/<int:pk>/propostas/<int:proposal_pk>/aceitar/', views.trade_proposal_accept, name='trade_proposal_accept'),
    path('trocas/<int:pk>/entrega/', views.trade_delivery_create_or_update, name='trade_delivery'),
    path('trocas/<int:pk>/cancelar/', views.trade_request_cancel, name='trade_request_cancel'),
    path('trocas/<int:pk>/mensagem/', views.trade_message_create, name='trade_message_create'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('register/', views.user_register, name='register'),
    path('api/listings/', ListingListAPIView.as_view(), name='api-listings'),
    path('api/register/', views.RegisterView.as_view(), name='api_register'),
    path('webhooks/mercadopago/', views.mercadopago_webhook, name='mp_webhook'),
    path('api/delivery/<int:order_pk>/status/', views.delivery_update_api, name='api_delivery_update'),
]